# Generated by Django 5.2.15 on 2026-07-10 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labequipment',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='in_charge',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='location',
        ),
        migrations.AddField(
            model_name='lab',
            name='building',
            field=models.CharField(default='Main', max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='floor',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='incharge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_code',
            field=models.CharField(default='LAB000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('computer', 'Computer Lab'), ('science', 'Science Lab'), ('electronics', 'Electronics Lab'), ('research', 'Research Lab'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='room_number',
            field=models.CharField(default='101', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_code', models.CharField(default='EQ000', max_length=30, unique=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('available_qty', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('repair', 'Needs Repair'), ('damaged', 'Damaged')], default='good', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance')], default='available', max_length=15)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='laboratory.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('assigned_technician', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='laboratory.equipment')),
            ],
        ),
        migrations.DeleteModel(
            name='LabBooking',
        ),
        migrations.DeleteModel(
            name='LabEquipment',
        ),
    ]
